;; (require 'escreen)
;; (global-set-key (kbd "C-z") 'escreen-prefix)
;; (mapc
;;  #'(lambda (pair) (eval `(define-key escreen-map (eval (kbd ,(first pair))) ,(second pair))))
;;  '(("0" 'escreen-goto-screen-0)
;;    ("1" 'escreen-goto-screen-1)
;;    ("2" 'escreen-goto-screen-2)
;;    ("3" 'escreen-goto-screen-3)
;;    ("4" 'escreen-goto-screen-4)
;;    ("5" 'escreen-goto-screen-5)
;;    ("6" 'escreen-goto-screen-6)
;;    ("7" 'escreen-goto-screen-7)
;;    ("8" 'escreen-goto-screen-8)
;;    ("9" 'escreen-goto-screen-9)
;;    ("?" 'escreen-help)
;;    ("a" 'escreen-get-active-screen-numbers)
;;    ("C-a" 'escreen-get-active-screen-numbers)
;;    ("g" 'escreen-get-current-screen-number)
;;    ("c" 'escreen-create-screen)
;;    ("C-c" 'escreen-create-screen)
;;    ("b" 'escreen-goto-screen)
;;    ("C-b" 'escreen-goto-screen)
;;    ("k" 'escreen-kill-screen)
;;    ("C-k" 'escreen-kill-screen)
;;    ("n" 'escreen-goto-next-screen)
;;    ("p" 'escreen-goto-prev-screen)))
